version: "3.3"
services:
  message_queue:
     container_name: message_queue
     image: redis
     expose: 
       - 6379
  restaurant_order:
      container_name: restaurant_order
      build: .
      ports:
        - 15000:15000
      depends_on:
        - restaurant_order_db
  restaurant_order_db:
    container_name: restaurant_order_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 23456
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - restaurant_order_db:/data/db
  restaurant_order_test:
    container_name: restaurant_order_test
    build: ./test
    depends_on:
      - restaurant_order
      - restaurant_order_db
    volumes:
      - ./test:/app

volumes:
  restaurant_order_db:
    name: restaurant_order_db